export const REQUEST_GET_TASKS = 'REQUEST_GET_TASKS';
export const REQUEST_ADD_TASK = 'REQUEST_ADD_TASK';
export const REQUEST_DELETE_TASK = 'REQUEST_DELETE_TASK';
export const REQUEST_EDIT_CHECK_TASK = 'REQUEST_EDIT_CHECK_TASK';
export const REQUEST_EDIT_TEXT_TASK = 'REQUEST_EDIT_TEXT_TASK';

export const RESOLVE_GET_TASKS = 'RESOLVE_GET_TASKS';
export const RESOLVE_ADD_TASK = 'RESOLVE_ADD_TASK';
export const RESOLVE_DELETE_TASK = 'RESOLVE_DELETE_TASK';
export const RESOLVE_EDIT_CHECK_TASK = 'RESOLVE_EDIT_CHECK_TASK';
export const RESOLVE_EDIT_TEXT_TASK = 'RESOLVE_EDIT_TEXT_TASK';

export const REQUEST_GET_COMMENTS = 'REQUEST_GET_COMMENTS';
export const REQUEST_ADD_COMMENT = 'REQUEST_ADD_COMMENT';

export const RESOLVE_GET_COMMENTS = 'RESOLVE_GET_COMMENTS';
export const RESOLVE_ADD_COMMENT = 'RESOLVE_ADD_COMMENT';

export const REQUEST_GET_TYPES = 'REQUEST_GET_TYPES';

export const RESOLVE_GET_TYPES = 'RESOLVE_GET_TYPES';

export const EDIT_ACTUAL_TYPE = 'EDIT_ACTUAL_TYPE';

export const ERROR_REQUEST = 'ERROR_REQUEST';
